// FLUTTER/DART
export 'dart:io';
export 'dart:async';
export 'dart:convert';
export 'package:flutter/material.dart';
export 'package:flutter/services.dart';

// PACKAGES
export 'package:gap/gap.dart';
export 'package:http/http.dart';
export 'package:go_router/go_router.dart';
export 'package:local_auth/local_auth.dart';
export 'package:jwt_decoder/jwt_decoder.dart';
export 'package:shared_preferences/shared_preferences.dart';
export 'package:flutter_secure_storage/flutter_secure_storage.dart';
export 'package:flutter_riverpod/flutter_riverpod.dart' hide AsyncError;

/// FILES
export 'package:test_mpp/core/const/app_const.dart';
export 'package:test_mpp/core/theme/app_theme.dart';
export 'package:test_mpp/core/widgets/app_bar.dart';
export 'package:test_mpp/core/theme/text_theme.dart';
export 'package:test_mpp/core/theme/color_theme.dart';
export 'package:test_mpp/core/theme/app_shadows.dart';
export 'package:test_mpp/core/router/router_keys.dart';
export 'package:test_mpp/core/theme/switch_theme.dart';
export 'package:test_mpp/core/helpers/app_snacks.dart';
export 'package:test_mpp/core/helpers/app_dialogs.dart';
export 'package:test_mpp/core/helpers/app_biometrics.dart';
export 'package:test_mpp/core/widgets/app_text_field.dart';
export 'package:test_mpp/core/router/router_provider.dart';
export 'package:test_mpp/core/helpers/field_validator.dart';
export 'package:test_mpp/features/users/data/user_data.dart';
export 'package:test_mpp/features/users/data/users_api.dart';
export 'package:test_mpp/features/auth/data/model/enum.dart';
export 'package:test_mpp/core/helpers/app_bottom_sheets.dart';
export 'package:test_mpp/core/extension/theme_extension.dart';
export 'package:test_mpp/features/users/view/users_page.dart';
export 'package:test_mpp/features/auth/data/api/auth_api.dart';
export 'package:test_mpp/features/auth/domain/auth_token.dart';

export 'package:test_mpp/core/extension/string_extension.dart';
export 'package:test_mpp/core/theme/elevated_button_theme.dart';
export 'package:test_mpp/features/auth/data/model/my_user.dart';
export 'package:test_mpp/core/widgets/squarre_icon_button.dart';
export 'package:test_mpp/core/preferences/user_preferences.dart';
export 'package:test_mpp/features/auth/domain/auth_service.dart';
export 'package:test_mpp/core/theme/input_decoration_theme.dart';
export 'package:test_mpp/features/auth/view/auth_login_page.dart';
export 'package:test_mpp/features/auth/data/model/auth_const.dart';
export 'package:test_mpp/core/widgets/app_progress_indicator.dart';
export 'package:test_mpp/features/auth/domain/auth_login_info.dart';
export 'package:test_mpp/features/users/view/widgets/user_tile.dart';
export 'package:test_mpp/features/auth/view/widgets/login_fields.dart';
export 'package:test_mpp/features/auth/view/widgets/signin_button.dart';
export 'package:test_mpp/features/auth/view/widgets/login_buttons.dart';
export 'package:test_mpp/features/users/view/widgets/user_list_widget.dart';
export 'package:test_mpp/features/users/view/widgets/crud_user_bottom_sheet.dart';
export 'package:test_mpp/features/auth/domain/providers/connection_provider.dart';
export 'package:test_mpp/features/users/domain/providers/user_list_provider.dart';
export 'package:test_mpp/features/auth/domain/providers/login_fields_provider.dart';
